# Generated by Django 3.2.5 on 2021-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210811_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(default='Other', to='blog.Tag'),
        ),
    ]
