# Generated by Django 3.2.5 on 2021-08-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(help_text='Hold down “Control”, or “Command” on a Mac, to select more than one.', to='blog.Tag'),
        ),
    ]
